---
- name: Uses combinations of collection, roles and modules
  gather_facts: True
  hosts: all
  collections:
    - irixjp.sample_collection_hello
  roles:
    - benthomasson.hello_role
    - hello
  tasks:
  - irixjp.sample_collection_hello.sample_get_locale:
    register: ret