---
- name: Uses collection and roles
  hosts: all
  gather_facts: false
  collections:
    - ibm.qradar
    - ericsysmin.system
  roles:
    - role: ericsysmin.system.ntp
  tasks:
    - name: Use a module from the collection
      qradar_log_source_management:
        name: "Ansible Collections Example Log Source"
        type_name: "Linux OS"
        state: present
        description: "Ansible Collections Example Log Source Description"