---
- name: deprecation warning
  hosts: localhost
  connection: local 
  gather_facts: false
  tasks:
  - name: Collect BIG-IP facts
    bigip_device_facts:
      gather_subset:
        - interfaces
        - vlans
    delegate_to: localhost
