---
- name: VMware Simple Indirect Node Test
  hosts: localhost
  gather_facts: false

  vars:
    vcenter_datacenter: "Eco-Datacenter"
    vcenter_cluster: "Eco-Cluster"
    vcenter_folder: "test-indirect"
    test_vm_name: "test-indirect-vm-{{ 9999 | random }}"
    vm_template_name: "rhel9"

  environment:
    VMWARE_HOST: "{{ vcenter_hostname | default(lookup('ansible.builtin.env', 'VMWARE_HOST')) }}"
    VMWARE_USER: "{{ vcenter_username | default(lookup('ansible.builtin.env', 'VMWARE_USER')) }}"
    VMWARE_PASSWORD: "{{ vcenter_password | default(lookup('ansible.builtin.env', 'VMWARE_PASSWORD')) }}"
    VMWARE_VALIDATE_CERTS: "{{ vcenter_validate_certs | default(lookup('ansible.builtin.env', 'VMWARE_VALIDATE_CERTS')) | default('False') }}"

  tasks:
    - name: Create VM from template
      vmware.vmware.deploy_folder_template:
        template_name: "{{ vm_template_name }}"
        vm_name: "{{ test_vm_name }}"
        vm_folder: "{{ vcenter_folder }}"
        cluster: "{{ vcenter_cluster }}"
        datacenter: "{{ vcenter_datacenter }}"

    - name: Delete VM
      community.vmware.vmware_guest:
        state: absent
        name: "{{ test_vm_name }}"
        folder: "{{ vcenter_folder }}"
        datacenter: "{{ vcenter_datacenter }}"
        force: true
